name: Reset Staging
on:
  schedule:
    - cron: '30 9 * * 1' # at 9:30 UTC on Monday
  workflow_dispatch:
jobs:
  reset-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: staging
      - name: Get current date
        id: date
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYY-MM-DD"
      - name: Reset branch to master
        run: |
          git fetch origin master
          git reset --hard origin/master
      - name: Last reset
        run: |
          echo ${{ steps.date.outputs.date }} > ./.github/last_staging_reset.md
          git add ./.github/last_staging_resets.md
          git commit -m "Staging reset on  ${{ steps.date.outputs.time}}"
      - name: Push to staging
        run: git push origin staging --force