name: Reset Staging
on:
  schedule:
    - cron: '30 9 * * 1' # at 9:30 UTC on Monday
  workflow_dispatch:
jobs:
  reset-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: staging
      - name: Get current date
        id: date
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYY-MM-DD"
      - name: Reset branch to main
        run: |
          git fetch origin main
          git reset --hard origin/main
      - name: Last reset
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          echo ${{ steps.date.outputs.time }} > ./.github/last_staging_reset.md
          git add ./.github/last_staging_reset.md
          git commit -m "Staging reset on  ${{ steps.date.outputs.time }}"
      - name: Push to staging
        run: git push origin staging --force